// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTb5aBYrQEivqLct7KtLZKWCCWV5II4w',
    appId: '1:996132571694:web:2af7914e160b6a5684adbf',
    messagingSenderId: '996132571694',
    projectId: 'lumeno-app',
    authDomain: 'lumeno-app.firebaseapp.com',
    storageBucket: 'lumeno-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRbmzN-p5oPnhPnidcJZTdG0Z3a7Booj4',
    appId: '1:996132571694:android:50ebb31df9b619aa84adbf',
    messagingSenderId: '996132571694',
    projectId: 'lumeno-app',
    storageBucket: 'lumeno-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKTdMX_zgQr_7ZPVhI96aTHxfP5PSLcAE',
    appId: '1:996132571694:ios:81f592a8f63af92684adbf',
    messagingSenderId: '996132571694',
    projectId: 'lumeno-app',
    storageBucket: 'lumeno-app.firebasestorage.app',
    iosBundleId: 'com.example.lumenoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKTdMX_zgQr_7ZPVhI96aTHxfP5PSLcAE',
    appId: '1:996132571694:ios:81f592a8f63af92684adbf',
    messagingSenderId: '996132571694',
    projectId: 'lumeno-app',
    storageBucket: 'lumeno-app.firebasestorage.app',
    iosBundleId: 'com.example.lumenoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxTb5aBYrQEivqLct7KtLZKWCCWV5II4w',
    appId: '1:996132571694:web:0f09269a3592506384adbf',
    messagingSenderId: '996132571694',
    projectId: 'lumeno-app',
    authDomain: 'lumeno-app.firebaseapp.com',
    storageBucket: 'lumeno-app.firebasestorage.app',
  );
}
